name: rentify
description: A clean Flutter restart for Rentify app
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2  
  image_picker: ^1.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3
  firebase_auth: ^6.1.1
  google_sign_in: ^6.2.1
  flutter_image_compress: ^2.3.0
  photo_view: ^0.15.0
  google_maps_flutter: ^2.7.0
  geolocator: ^13.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

